# .github/workflows/release.yml

name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for the commit SHA

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Get Commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.sha_short }}
          name: "Release ${{ steps.vars.outputs.sha_short }}"
          prerelease: false
          files: build/libs/forceitem-battle-1.0-SNAPSHOT-all.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}